SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM (
    SELECT ID, FISH_TYPE, 
           CASE WHEN LENGTH IS NULL OR LENGTH <= 10 THEN 10
                ELSE LENGTH 
           END AS LENGTH,
           TIME
    FROM FISH_INFO
) AS ADJUSTED_FISH_INFO;