-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, SUM(OFFLINE_SALE.SALES_AMOUNT * PRODUCT.PRICE) as SALES
FROM PRODUCT 
JOIN OFFLINE_SALE on OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES desc, PRODUCT.PRODUCT_CODE asc;
